### ISSUE TITLE
Upgrade to operator-sdk v1.5.0

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/k8gb#376]
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.5.0/

**Comment by kuritka** [comment]
@yruslan @k0da @somaritane 
 In order to migration Operator SDK v1.5.0: [For Go-based operators, migrate your project to use the project version stable](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.5.0/#for-go-based-operators-migrate-your-project-to-use-the-project-version-stable),
Should we release  k8gb@v1.0.0  than ?

**Comment by somaritane** [comment]
@kuritka , are there any breaking changes that this osdk migration might introduce to k8gb behavior (~ public API)?
If the answer is "no", then according to https://semver.org/ there's no need to bump major version of k8gb.

**Comment by kuritka** [comment]
@ytsarev , @somaritane  oh I see, than v3 (viz next step)
thx for clarification!

**Comment by somaritane** [comment]
> @ytsarev , @somaritane oh I see, than v3 (viz following step)

@ytsarev, @kuritka just to clarify, we're talking about osdk/kubebuilder project config version change from v3-alpha to 3, right?

If yes, then it has nothing to do with k8gb versioning, unless it really brings breaking changes in k8gb project public API itself (ie if it causes breaking changes in glsb schema from user perspective), which we yet have to analyze.

Only in this case that would be transition from v0.7.7 to v1.0.0 (incompatible API changes), but not to v3

Otherwise, it would be v0.7.7-> v0.8.0 (added functionality in a backwards compatible manner)

**Comment by kuritka** [comment]
@somaritane , I want through v1.4.0 and 1.5.0 upgrade. Having some build issues related to bumping controller-runtime.

The version change I mentioned is related with file `PROJECT`. No API changes;  we go as planned `v0.7.7-> v0.8.0`

**Comment by somaritane** [comment]
@kuritka thanks for clarification! 👍
